Entrega do Lab2
PauloAguiar/ces27-lab2 pull request #5
Opened 2016-10-12 00:14 UTC by miltoneiji

Entrega do Lab2 para code review.

2016-10-14 01:26 UTC, PauloAguiar requested changes
Tirando o problema com o search, o restante do código parace estar correto.

2016-10-14 01:26 UTC, PauloAguiar commented on common/consistenthash/consistenthash.go
> +        if node.HashId > hashValue {
E se todos os elementos tiverem um hash menor que o calculado pra key?

2016-10-14 19:45 UTC, miltoneiji commented on common/consistenthash/consistenthash.go
> +        if node.HashId > hashValue {
Se todos os elementos tiverem um hash menor que o calculado para a key, a condição do if nunca será obedecida. Assim, tal função retornará idx = r.Nodes.Len(), que no caso é uma posição inválida. Mas pesquisando em quais métodos a função search era  chamada eu verifiquei que você ja tinha tratado o caso de quando a função search retorna idx = r.Nodes.Len(). (a saber: RemoveNode e Get).

2016-10-14 20:04 UTC, PauloAguiar commented on common/consistenthash/consistenthash.go
> +        if node.HashId > hashValue {
Mas se a gente for olhar especificamente o papel da função search, incluindo o comentário acima dela: 

```go
// search will find the index of the node that is responsible for the range that
// includes the hashed value of key.
func (r *Ring) search(key string) int {
```

Você consideraria esse comportamento correto? Provavelmente o seu código vai ter um erro no corretor automático. Ele simplesmente vai testar a API esperada da biblioteca consistenthash, e não se o código está funcionando corretamente.

2016-10-14 20:20 UTC, miltoneiji commented on common/consistenthash/consistenthash.go
> +        if node.HashId > hashValue {
Entendi. Arrumei la, agora quando ele não acha um node com hash maior ele retorna o index do node com menor hash.

2016-10-16 21:49 UTC, PauloAguiar approved these changes

2019-10-11 21:04 UTC, closed without merging